export const GPE = "Greater Planar Essence";
export const LPS = "Large Prismatic Shard";
export const AD = "Arcane Dust";
export const VC = "Void Crystal";
export const SPS = "Small Prismatic Shard";
export const PA = "Primal Air";
export const PS = "Primal Shadow";
export const PF = "Primal Fire";
export const PE = "Primal Earth";
export const PL = "Primal Life";
export const PW = "Primal Water";
export const PM = "Primal Mana";
export const FL = "Fel Lotus";
export const LE = "Living Essence";
export const LPE = "Lesser Planar Essence";
export const EO = "Eternium Ore";
export const PN = "Primal Nether";
export const EoMS = "Elixir of Major Strength";
export const PMIGHT = "Primal Might";

/*VANILLA*/
export const MHP = "Major Healing Potion";
export const MMP = "Major Mana Potion";
export const EoF = "Essence of Fire";
export const SRS = "Small Radiant Shard";
export const AQM = "Aquamarine";
export const LNE = "Lesser Nether Essence";
export const LBS = "Large Brilliant Shard";
export const RO = "Righteous Orb";
